version: '3.8'

services:
  server:
    image: blogbackendproduction
    build: ./backend
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 3003:3003
  app:
    image: blogfrontendproduction
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - 3000:3000