version: '3.8'

services:
  server:
    image: blogbackendproduction
    build: ./backend
    volumes:
      - ./todo-backend:/usr/src/app
  app:
    image: blogfrontendproduction
    build: ./frontend
    volumes:
      - ./todo-frontend:/usr/src/app